services:
  wordpress:
    image: wordpress:6.8
    restart: unless-stopped
    links:
      - mysql
    depends_on:
      - mysql
    env_file:
      - .env
    volumes:
      - ./public_html:/var/www/html
      - ./WORDPRESS_CONFIG_EXTRA:/etc/WORDPRESS_CONFIG_EXTRA
      - ./plugins:/plugins
    ports:
      - "8067:80"

  wpcli:
    image: wordpress:cli
    user: 1000:1000
    depends_on:
      - wordpress
    env_file:
      - .env
    volumes:
      - ./public_html:/var/www/html
      - ./WORDPRESS_CONFIG_EXTRA:/etc/WORDPRESS_CONFIG_EXTRA
      - ./plugins:/plugins
  mysql:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${WORDPRESS_DB_NAME}
      MYSQL_USER: ${WORDPRESS_DB_USER}
      MYSQL_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - ./db:/var/lib/mysql
